name: glimpse
description: A minimalistic modal sheet inspired by AirPods.
version: 0.0.1
repository: https://github.com/breitburg/glimpse

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  screen_corners: ^0.6.0
  smooth_corner: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

flutter:
